### PR TITLE
Added slovenian translation

### PR DESCRIPTION
**Pull request by buma**
Added slovenian translation

### CODE REVIEW

**Comment by forslund** [comment]
Hi @buma, we're preparing to import translations from our translation system https://translate.mycroft.ai. It would be better if you added the translations there.

**Comment by buma** [comment]
I tried to but I can't add new language. I can send you the po files.

**Comment by forslund** [comment]
Slovenian was added yesterday (~20 hours ago) so it should be possible now.

**Comment by buma** [comment]
Weird that Slovenian was added just 20 hours ago. Is there any way I can upload po files to translation system, because it will take very long to retranslate everything again. This skill has 6 strings which is nothing, but date-time, weather or timer have many more strings and I don't want to write them line by line on web interface when I've already translated at home.

**Comment by KathyReid** [comment]
Hi there @buma, thanks so much for the Slovenian translations - it was I who added in the new languages yesterday, I added about a dozen or so. Can you attach the `*.po` files to this PR and I'll see if I can add them straight to the filesystem? We don't have uploads enabled yet. 
Kind regards, Kathy

**Comment by buma** [comment]
Thank you @KathyReid for enabling Slovenian translation. I've added skill-stop to [gist](https://gist.github.com/buma/c976f434ef64c9fc9ea6c90ff161f6a0). If this works I'll add other po files.

I have one question. What to do when there are more possible translations in po files?
Just add more in new line?
For example "be quiet" can be translated to both "bodi tiho" and "tiho bodi". And "tišina" also means the same as "tiho" aka silence.

**Comment by KathyReid** [comment]
@buma thank you so much for the `.po` file, I will add this to our test server first to ensure that it works and then if it does I will add it to https://translate.mycroft.ai. 

What I'd recommend is translating _the most appropriate_ phrase. This can be a little difficult, because it's not easy to infer context from just the translations shown in Mycroft Translate.

**Comment by KathyReid** [comment]
@buma that looks like it worked! :+1: 

https://translate.mycroft.ai/sl/mycroft-skills/skill-stop-sl.po

**Comment by krisgesling** [comment]
Hey there, given how outdated this PR is I'm going to close it, but let me know if we should be adding Slovenian to our regular translation sync.

**Pull request closed without merging**
