### PR TITLE
Added stopp (for google STT)

### PR DESCRIPTION
**Pull request by AZAZ78**
A single stop is recognized by google STT as "stopp" in de-de. Add this to the intent vocab.

### How to use this template
Under each heading below is a short outline of the information required. When submitting a PR, please delete this text and replace it with your own. 

The CLA section can be deleted entirely.

#### Description
A single stop is recognized by google STT as "stopp" in de-de. Add this to the intent vocab.

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [x] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Set lang to de-de and use google STT. After start of e.g. npr or radio skill only say "Hey Mycroft, Stop" which is recognized as "Hey Mycroft, stopp".

#### Documentation
n.a.

#### CLA
To protect you, the project, and those who choose to use Mycroft technologies in systems they build, we ask all contributors to sign a Contributor License Agreement.

This agreement clarifies that you are granting a license to the Mycroft Project to freely use your work.  Additionally, it establishes that you retain the ownership of your contributed code and intellectual property.  As the owner, you are free to use your code in other work, obtain patents, or do anything else you choose with it.

If you haven't already signed the agreement and been added to our public [Contributors repo](https://github.com/mycroftAI/contributors) then please head to https://mycroft.ai/cla to initiate the signing process.

Is this really necessary for this small change?

If you have any further questions, please contact me via gitter.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Azaz, thanks for this small but I'm sure very useful contribution.

The CLA seems ridiculous for such a small change however from a project perspective we require it for every PR, no matter how many characters change.

Given it is a word, if you'd prefer not to, then I'm sure someone else from our community that has signed the CLA would be happy to submit it.

**Comment by AZAZ78** [comment]
Ok, i will do the signing. I am currently developing skills for Neato Vacuum Cleaner, EIB/KNX Homeautomation and the Bring! Shopping list. At least when i want to share them its necessary to sign i assume;-)

**Comment by krisgesling** [comment]
Hey, that sounds really cool, I look forward to seeing those!

For your own Skills you don't need to sign the CLA, only when contributing to our official repo's. To have your Skill in the Marketplace it just needs to have a compatible open license so that we can distribute it.

**Comment by AZAZ78** [comment]
CLA is signed

**Comment by krisgesling** [comment]
Received, thanks!

**Pull request merged**
