### PR TITLE
Add and fix missing french translation

### PR DESCRIPTION
**Pull request by goldyfruit**
Add and fix French translation.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Gaëtan, with the accents, I presume you're seeing most STT services returning transcripts without them? 

Happy to go with what works in the most cases for now. But wondering if this is something we should be mindful of when building out improved translation layers? Should we support both accented and non-accented forms?

**Comment by goldyfruit** [comment]
@krisgesling I got weird behavior with the accents, not sure why (yet), for example I'm not able to stop the speaking.

**Comment by krisgesling** [comment]
Is the STT returning non-accented strings? Or even with accents in the utterance string you are still seeing problems?

**Comment by goldyfruit** [comment]
@krisgesling seems to work with the accent now, I'm confused... I reverted all the changes related to the accents in my PR.

image
```
2022-09-28 20:47:25.278 | DEBUG    |     1 | mycroft.skills.intent_service:_normalize_all_utterances:72 | Utterances: [('arrêter',)]
2022-09-28 20:47:25.303 | DEBUG    |     1 | mycroft.skills.intent_services.padatious_service:_match_level:47 | Padatious Matching confidence > 0.95
2022-09-28 20:47:25.384 | DEBUG    |     1 | Mark2 | Stop received
```
```
2022-09-28 20:45:21.336 | DEBUG    |     1 | mycroft.client.speech.listener:transcribe:224 | STT: arrêter
2022-09-28 20:45:21.341 | INFO     |     1 | __main__:handle_utterance:76 | Utterance: ['arrêter']
```
It worked by voice as well...

**Comment by krisgesling** [comment]
Yeah weird... I'm guessing that this will be a problem with certain STT's though. So good thing for us to think about in the future.

Edit: same with hyphenated words, I can easily see scenarios where some engines return hyphenated, others return with a space.

**Pull request merged**
